### ISSUE TITLE
Add support for high-DPI monitors

### ISSUE THREAD

**Issue by shad1w** [BBasile/Coedit#151] opened 2017-05-27 02:27 UTC
Currently some UI elements are not fully visible on high-DPI monitors (4K in this case, but might be the case for lower resolutions as well).

UI elements are generally scaled for what appears to be correct for a FullHD resolution while having the correct font size for my native resolution.

Here is an image of what it currently looks like for me:  
![image](https://cloud.githubusercontent.com/assets/22195087/26517188/bb278c2c-4293-11e7-83be-d12787422fa7.png)

I'm using Coedit on Windows 10 x64.

**Comment by shad1w** [comment] 2017-05-27 02:35
A workaround for this is to set the compatibility options of the program to let the system override the scaling on high DPI monitors.

Afterwards you need to reset the configuration of Coedit. I simply deleted the Coedit folder from `%AppData%`, but be aware that this will probably delete all settings!

**Comment by BBasile** [comment] 2017-05-27 04:25
I'll provide betas in order to test an explicit option for HDP. Probably not before the beginning of the summer (need Lazarus 1.8).

**Comment by BBasile** [comment] 2017-07-05 14:37
Delayed. Much.

**Comment by BBasile** [comment] 2018-01-10 22:14
Can you give a try this weekend, i can upload an alpha in the next days ?
On linux and with KDE i was able to verify that it works because everything can be scaled in a special setting but for Windows i'm not sure if i can verify by myself.

**Comment by BBasile** [comment] 2018-01-10 22:19
linux KDE, scaling 1.3X

![scaled_1 3](https://user-images.githubusercontent.com/16154339/34798501-a5ad1c68-f65c-11e7-9917-a80028a05060.png)

**Comment by BBasile** [comment] 2018-01-12 21:45
An alpha with auto H-DPI support is here https://github.com/BBasile/Coedit/releases/tag/v3.6.0-alpha.1

**Comment by lainz** [comment] 2018-01-14 19:05
Hi, I commented on the Lazarus forum.

Looks fine, but the filters height are not fine.
![coedit1](https://user-images.githubusercontent.com/4131395/34919509-13fac028-f944-11e7-8270-d795206f1ee5.PNG)

The options height are wrong also.
![coedit2](https://user-images.githubusercontent.com/4131395/34919520-39ba9144-f944-11e7-900c-947f8151c409.PNG)

Another
![coedit3](https://user-images.githubusercontent.com/4131395/34919528-51cf8726-f944-11e7-92ff-18f4bca66870.PNG)

About
![coedit4](https://user-images.githubusercontent.com/4131395/34919547-8111c36e-f944-11e7-8310-97785abc37d6.PNG)

Some panels at the left
![coedit5](https://user-images.githubusercontent.com/4131395/34919559-b84b72bc-f944-11e7-8c07-b93f9fcad8d9.PNG)

**Comment by BBasile** [comment] 2018-01-14 20:00
Thanks guys. Looks like there's more problems than expected. Things like filters and options are stock LCL controls. I the same controls are Okay in Laz that's probably because they do something special with them.

**Comment by BBasile** [comment] 2018-01-17 18:15
I solved most of the issues now. Unfortunately i think that the icons will remain as it. You can already check the progress for linux: https://github.com/BBasile/Coedit/releases/download/v3.6.0-alpha.1/coedit.linux64.updated.zip. Maybe give me your opinions about the toolbar icons. I tested by changing the font PPP but i still have a classic 23'' 1920*1080 in front of my eyes...So i'm biased about the icon thing.

**Comment by lainz** [comment] 2018-01-17 19:04
Lazarus team solved the icons problem for the IDE using 150% (36x36) and 200% (48x48) icon sizes, along the 100% (24x24).

**Comment by BBasile** [comment] 2018-01-17 19:15
I plan to rescale the 32x32 versions to 24x24 and always use the 24 version. Earlier today i tred to adapt my toolbar and it didn't work (https://github.com/BBasile/Coedit/blob/master/src/ce_dsgncontrols.pas). The idea was to keep the 'resourceName' property but to look if there's a resource with a trailing '32' '24' etc and loads this one instead when the button size allows this. The problem is that the toolbar itself isn't scaled (even if buttons managed to load the bigger resource).

**Comment by lainz** [comment] 2018-01-17 20:29
```
height := 30;
ButtonHeight := 28;
ButtonWidth := 28;
```

There is your problem. You should scale values that you input by code.

`height := ScaleX(30, 96)`

96 is the 100% of zoom under Windows, for example.

**Comment by BBasile** [comment] 2018-01-17 20:33
This is part of what i tried. I read your answer on Laz forums where you told me about the scaleX and scaleY functions. Will try again. Maybe i've made an error today.

**Comment by BBasile** [comment] 2018-01-19 14:28
Icons, todo:

- [ ] editor gutter
- [ ] DUB project editor, the JSON icons. SVGs are on another machine.
- [ ] GDB commander, icon "bug magnify", goota look for other sizes in Laz or replace it.
- [ ] All the main menu

**Comment by BBasile** [comment] 2018-01-20 05:06
I think this is good now. There's a new alpha with a full support for scaling:

https://github.com/BBasile/Coedit/releases/tag/v3.6.0-alpha.2

Still a few icons missing but meh.

**Comment by BBasile** [comment] 2018-01-20 05:07
ping @zorael too, if you have 5 mins this week end.

**Comment by opticron** [comment] 2018-01-20 05:49
I get a crash when trying to run the latest alpha:
[FORMS.PP] ExceptionOccurred 
  Sender=EResNotFound
  Exception=Resource "BOOK_GREY32" not found
  Stack trace:
  $00000000004A84F1
  $00000000004A872F
  $0000000000921D7C
  $00000000004FAF5E
  $0000000000513A67
  $0000000000510C35
  $000000000042F091
  $0000000000433CC8
  $000000000043C1D8
TApplication.HandleException Resource "BOOK_GREY32" not found
  Stack trace:
  $00000000004A84F1
  $00000000004A872F
  $0000000000921D7C
  $00000000004FAF5E
  $0000000000513A67
  $0000000000510C35
  $000000000042F091
  $0000000000433CC8
  $000000000043C1D8

**Comment by BBasile** [comment] 2018-01-20 07:34
damn i made a typo in the filenames...gotta update everything.

**Comment by BBasile** [comment] 2018-01-20 07:47
Thanks for the quick report, the files are updated.

**Comment by zorael** [comment] 2018-01-20 10:28
Icons look much better.

The Options editor column width is still [wrong](https://i.imgur.com/3QEUzuA.png), but maybe this is the case on non-hidpi as well? The longest option seems to be `closeCompletionCharsWithSpace`, and as the picture shows, it's cropped to `closeCompletionCha`. Widening it seems to persist only through the program's lifetime (closing and restarting resets).

I only have some minor nitpicks other than that (principle of least surprise on some things, what is "MODI..."? etc), but they're not related to scaling. Looks good.

**Comment by BBasile** [comment] 2018-01-20 10:35
Yeah i can confirm that there's a problem with the splitter in the property inspector used by the option editor. It's not saved but the value i set programatically is not handled as it should. For now i can't say if it's a bug with Lazarus components or me no getting something.

I don't see what is this "MODI..." thing ?
I'm on IRC now if you want to explain.

**Comment by BBasile** [comment] 2018-01-20 10:42
Another todo, status bar autoscaling:

![](https://i.imgur.com/kNy1YXL.png)

MODI... -> MODIFIED

**Comment by BBasile** [comment] 2018-01-20 11:23
Also Sync edit icon in the editor gutter.

**Comment by opticron** [comment] 2018-01-20 14:56
I see the MODI... issue as well. Also, do these controls look right?
![coedit-edit-controls](https://user-images.githubusercontent.com/2607100/35184792-c358362a-fdbf-11e7-88cf-f3854f72fbc6.png)

**Comment by BBasile** [comment] 2018-01-20 15:47
Yeah. The tree of the project inspector apparently. Cut on the right.

**Closed** 2018-01-22 00:33 UTC
Labels: FCL-LCL, IMPROVEMENT
